version: '3.8'

services:

  backend:
    build:
      context: ./server
    container_name: techmine_fastapi_server
    ports:
      - "8800:8800"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  frontend:
    build:
      context: ./techmine
    container_name: techmine_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./techmine/build/web:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
  
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: techmine_nginx_server
    ports:
      - "80:80"
      # - "443:443" if HTTPS
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
