version: '3.8'

services:

  nginx-proxy:
    build:
      context: ./proxy
    container_name: techmine_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
      - gml-web-proxy
    volumes:
      - ./server/app/media:/var/www/media
    networks:
      - app-network
      
  backend:
    build:
      context: ./server
    container_name: techmine_fastapi_server
    ports:
      - "8800:8800"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./server/app/media:/server/app/media
    networks:
      - app-network

  frontend:
    build:
      context: ./techmine
    container_name: techmine_frontend
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
  
  # the services of GML-launcher
  gml-web-api:
    image: ghcr.io/gml-launcher/gml.web.api:v2025.2
    container_name: gml-web-api
    restart: always
    volumes:
      - /srv/gml/data/GmlBackend:/root/${PROJECT_NAME}
      - gml-system-data:/app/database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8082;
      - SECURITY_KEY=${SECURITY_KEY}
      - PROJECT_NAME=${PROJECT_NAME}
      - MARKET_ENDPOINT=${MARKET_ENDPOINT}
      - PROJECT_DESCRIPTION=${PROJECT_DESCRIPTION}
      - PROJECT_POLICYNAME=${PROJECT_POLICYNAME}
      - PROJECT_PATH=${PROJECT_PATH}
      - SERVICE_TEXTURE_ENDPOINT=${SERVICE_TEXTURE_ENDPOINT}
      - TZ=Europe/Moscow
    user: "${UID}:${GID}"
    networks:
      - app-network

  gml-web-proxy:
    image: ghcr.io/gml-launcher/gml.web.proxy:v2025.2
    container_name: gml-web-proxy
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;
    user: "${UID}:${GID}"
    networks:
      - app-network
    depends_on:
      - gml-web-api
      - gml-web-frontend
      - gml-web-skins

  gml-web-frontend:
    image: ghcr.io/gml-launcher/gml.web.client:v2025.2
    container_name: gml-web-frontend
    restart: always
    networks:
      - app-network
    environment:
      - TZ=Europe/Moscow

  gml-web-skins:
    image: ghcr.io/gml-launcher/gml.web.skin.service:v2025.2
    container_name: gml-web-skins
    restart: always
    networks:
      - app-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8085;
      - TZ=Europe/Moscow
    user: "${UID}:${GID}"
    volumes:
      - /srv/gml/data/TextureService:/app/Storage
  

networks:
  app-network:
    driver: bridge

volumes:
  gml-system-data:
