"""add ip, port columns in servers table

Revision ID: 664c9ff62c6d
Revises: 653377798228
Create Date: 2025-10-13 14:56:53.772850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664c9ff62c6d'
down_revision: Union[str, Sequence[str], None] = '653377798228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('servers', sa.Column('port', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'port')
    op.drop_column('servers', 'ip')
    # ### end Alembic commands ###
