"""add cloak_url, avatar_url to Settings

Revision ID: 653377798228
Revises: 329064c9c18c
Create Date: 2025-10-09 15:18:40.496652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653377798228'
down_revision: Union[str, Sequence[str], None] = '329064c9c18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('cloak_url', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('avatar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'avatar_url')
    op.drop_column('settings', 'cloak_url')
    # ### end Alembic commands ###
